sudo: required

env:
    matrix:
        - PHP=7.1
        - PHP=7.2

services:
    - docker

before_script:
    - sudo sysctl -w vm.max_map_count=262144
    - cp docker/.env.dist docker/.env
    - bash -c 'sed -i "s/7.1/$PHP/g" docker/.env'
    - bash -c 'sed -i "/\- ..\/sql:\/var\/lib\/mysql/d" docker/docker-compose.yml.dist'
    - bash -c 'sed -i "s/.\/logs\/nginx\//\/tmp\/nginx/g" docker/docker-compose.yml.dist'
    - cd docker
    - bash docker.sh -d
    - docker exec -i -u www-data np_php bash -c "cd ../; rm -rf www; composer create-project symfony/website-skeleton www"
    - docker-compose stop
    - rm nginx/default.conf.dist nginx/silverstripe4.conf.dist
    - bash docker.sh -d
    - docker exec -i -u www-data np_php bash -c "composer require encore"

script:
    - docker exec -i -u www-data np_php bash -c "php bin/phpunit"
    - docker exec -i -u www-data np_php bash -c "yarn install"
    - docker exec -i -u www-data np_php bash -c "yarn build"
